plugins {
    alias(libs.plugins.android.application)
    id("com.google.gms.google-services")
}

android {
    namespace 'com.alaka_ala.florafilm'
    compileSdk 35

    defaultConfig {
        applicationId "com.alaka_ala.florafilm"
        minSdk 28
        //noinspection ExpiredTargetSdkVersion
        targetSdk 28
        versionCode 57
        // 1.0.0_rs Версия RuStore
        // 1.0.0_pm - PlayMarket
        // 1.0.0_app - AppStore
        // 1.0.0_nt - Нативное (прямое) обновление через встроенный менеджер в приложении
        versionName "1.0.57_nt"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildFeatures {
        viewBinding true
        buildConfig true
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

def room_version = "2.6.1"

dependencies {

    implementation "androidx.room:room-runtime:$room_version"
    annotationProcessor "androidx.room:room-compiler:$room_version"
    implementation "androidx.localbroadcastmanager:localbroadcastmanager:1.1.0"

    implementation libs.appcompat
    implementation libs.material
    implementation libs.activity
    implementation libs.constraintlayout
    implementation libs.navigation.fragment
    implementation libs.navigation.ui
    implementation libs.androidx.navigation.fragment
    implementation libs.androidx.navigation.ui
    implementation libs.androidx.cardview
    implementation libs.firebase.auth
    implementation libs.androidx.recyclerview
    implementation libs.androidx.legacy.support.v4
    implementation libs.androidx.viewpager2
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core

    // Picasso не нуждается в представлении
    implementation 'com.squareup.picasso:picasso:2.8'
    // JSOUP для парсинга HTML страниц с сайтов
    implementation 'org.jsoup:jsoup:1.15.3'
    // Плеер EXOPlayer
    implementation 'com.google.android.exoplayer:exoplayer:2.19.1'
    // Дешифратор вроде, может Html расшифровать/ Unicode тоже вроде как, (давно не использовал)
    implementation group: 'org.apache.commons', name: 'commons-lang3', version: '3.12.0'
    // Гугловский Gson, использую только для JsonParser
    implementation 'com.google.code.gson:gson:2.10.1'
    // вроде используется для FileUtils
    implementation 'commons-io:commons-io:2.13.0'
    // Яндекс метрика
    implementation 'io.appmetrica.analytics:analytics:7.10.0'

    // Не помню для чего они
    implementation 'org.bouncycastle:bcprov-jdk15on:1.69'
    implementation 'org.bouncycastle:bcpkix-jdk15on:1.69'


    implementation "androidx.swiperefreshlayout:swiperefreshlayout:1.1.0"   // Обновление экрана (потянуть сверху вниз для обновления)


    implementation 'jp.wasabeef:blurry:4.0.1'    // эффект размытия


    implementation 'com.airbnb.android:lottie:6.6.4'    // Анимации lottie


    implementation 'com.github.chrisbanes:PhotoView:2.3.0'  // Увеличение изображений

    // SSL
    implementation 'info.guardianproject.netcipher:netcipher:2.1.0'
    implementation 'org.conscrypt:conscrypt-android:2.5.3'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.9.0'


    implementation 'com.google.firebase:firebase-database:22.0.0' // Или актуальная версия

    // Firebaseimplementation 'com.frostwire:jlibtorrent-android-arm:1.2.0.18'

    def jlibtorrent_version = '2.0.12.5' // change version for latest

    // ALL ARCHITECTURES need the java .class wrappers jlibtorrent.jar
    implementation 'com.frostwire:jlibtorrent:' + jlibtorrent_version

    // ANDROID (needs all of them for most projects if you want to maximize compatibility)
    implementation 'com.frostwire:jlibtorrent-android-arm:' + jlibtorrent_version
    implementation 'com.frostwire:jlibtorrent-android-arm64:' + jlibtorrent_version
    implementation 'com.frostwire:jlibtorrent-android-x86:' + jlibtorrent_version
    implementation 'com.frostwire:jlibtorrent-android-x86_64:' + jlibtorrent_version

    // libsu for robust shell commands
    def libsuVersion = '3.2.1'
    implementation "com.github.topjohnwu.libsu:core:${libsuVersion}"


}